title:               NieR Automata Theme
tagline:             'A NieR theme for Jekyll'
description:          'A theme that replicates the NieR: Automata in-game menu.'
url:                 
baseurl:             ''

plugins:
  - jekyll-assets

sass:
  style: compressed

kramdown:
  auto_ids: true
  input: GFM
